class Solution {
public:
    int numberOfSubmatrices(vector<vector<char>>& grid) {
        int cnt=0;
        
        int m=grid.size();
        int n=grid[0].size();
        vector<vector<int>> cumSumX(m,vector<int> (n,0));
        vector<vector<int>> cumSumY(m,vector<int> (n,0));
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){

                cumSumX[i][j]=(grid[i][j]=='X' ? 1 : 0);
                cumSumY[i][j]=(grid[i][j]=='Y' ? 1 : 0);

                if(i-1 >=0){
                    cumSumX[i][j]+=cumSumX[i-1][j];
                    cumSumY[i][j]+=cumSumY[i-1][j];
                }

                if(j-1 >=0){
                    cumSumX[i][j]+=cumSumX[i][j-1];
                    cumSumY[i][j]+=cumSumY[i][j-1];
                }

                if(i-1 >=0 && j-1>=0){
                    cumSumX[i][j]-=cumSumX[i-1][j-1];
                    cumSumY[i][j]-=cumSumY[i-1][j-1];
                }

                if(cumSumX[i][j]==cumSumY[i][j] && cumSumX[i][j]>0){
                    cnt++;
                }
            }
        }
        return cnt;
    }
};